/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const HeroesLazyImport = createFileRoute('/heroes')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const HeroesLazyRoute = HeroesLazyImport.update({
  id: '/heroes',
  path: '/heroes',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/heroes.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/heroes': {
      id: '/heroes'
      path: '/heroes'
      fullPath: '/heroes'
      preLoaderRoute: typeof HeroesLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/heroes': typeof HeroesLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/heroes': typeof HeroesLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/heroes': typeof HeroesLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/heroes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/heroes'
  id: '__root__' | '/' | '/heroes'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  HeroesLazyRoute: typeof HeroesLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  HeroesLazyRoute: HeroesLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/heroes"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/heroes": {
      "filePath": "heroes.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
